package com.fitconnect.android.sports.registry

import com.fitconnect.android.sports.domain.CompetitionType
import com.fitconnect.android.sports.domain.EnvironmentKind
import com.fitconnect.android.sports.domain.MetricDefinition
import com.fitconnect.android.sports.domain.MetricKind
import com.fitconnect.android.sports.domain.MetricValueType
import com.fitconnect.android.sports.domain.OlympicStatus
import com.fitconnect.android.sports.domain.ParticipationKind
import com.fitconnect.android.sports.domain.Seasonality
import com.fitconnect.android.sports.domain.SkillLevel
import com.fitconnect.android.sports.domain.SportCategory
import com.fitconnect.android.sports.domain.SportDefinition
import com.fitconnect.android.sports.domain.SportId
import com.fitconnect.android.sports.domain.TrainingType
import com.fitconnect.android.sports.domain.WearableCapability

/**
 * Configuration seed for the Sports Registry. Adding a sport = append a
 * [SportDefinition] here (or register via plugin) — never patch app screens.
 */
object DefaultSportsCatalog {

    fun seed(registry: SportsRegistry) {
        definitions().forEach { def ->
            val result = registry.register(def, pluginId = "fitconnect.catalog.v1")
            check(result is RegistryValidation.Ok) {
                "Failed to seed ${def.id.value}: ${(result as RegistryValidation.Err).reasons}"
            }
        }
    }

    fun definitions(): List<SportDefinition> = listOf(
        sport(
            id = SportId.RUNNING,
            name = "Running",
            category = SportCategory.ENDURANCE,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Run",
            equipment = listOf("Shoes", "Watch"),
            required = listOf(m("pace", "Pace", "min/km"), m("distance", "Distance", "km", MetricValueType.DISTANCE)),
            optional = listOf(
                m("cadence", "Cadence", "spm"),
                m("vo2max", "VO2max", "ml/kg/min"),
                m("gct", "Ground Contact Time", "ms"),
                m("gap", "GAP", "min/km"),
            ),
            performance = listOf("pace", "vo2max", "consistency"),
            recovery = listOf("hrv", "sleep", "soreness"),
            risk = listOf("acwr", "sudden_mileage_spike"),
            wearables = setOf(WearableCapability.GPS, WearableCapability.HEART_RATE, WearableCapability.HRV, WearableCapability.HEALTH_CONNECT, WearableCapability.WEAR_OS),
            training = setOf(TrainingType.ENDURANCE, TrainingType.INTERVAL, TrainingType.RECOVERY),
            competition = setOf(CompetitionType.RACE, CompetitionType.PERSONAL_CHALLENGE, CompetitionType.VIRTUAL_CHALLENGE),
        ),
        sport(
            id = SportId.CYCLING,
            name = "Cycling",
            category = SportCategory.ENDURANCE,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Ride",
            equipment = listOf("Bike", "Power meter", "Helmet"),
            required = listOf(m("power", "Power", "W"), m("speed", "Speed", "km/h")),
            optional = listOf(
                m("ftp", "FTP", "W"),
                m("cadence", "Cadence", "rpm"),
                m("np", "Normalized Power", "W"),
                m("tss", "TSS", ""),
            ),
            performance = listOf("ftp", "np", "tss"),
            recovery = listOf("hrv", "sleep"),
            risk = listOf("acwr", "overreaching"),
            wearables = setOf(WearableCapability.POWER, WearableCapability.GPS, WearableCapability.HEART_RATE, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.ENDURANCE, TrainingType.INTERVAL, TrainingType.COMPETITION_PREP),
            competition = setOf(CompetitionType.RACE, CompetitionType.TIME_TRIAL, CompetitionType.VIRTUAL_CHALLENGE),
        ),
        sport(
            id = SportId.SWIMMING,
            name = "Swimming",
            category = SportCategory.WATER,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Swim",
            equipment = listOf("Goggles", "Suit"),
            required = listOf(m("pace_100", "Pace /100m", "min"), m("distance", "Distance", "m", MetricValueType.DISTANCE)),
            optional = listOf(
                m("swolf", "SWOLF", "", MetricValueType.SCORE),
                m("stroke_rate", "Stroke Rate", "spm"),
                m("lap_time", "Lap Time", "s", MetricValueType.DURATION),
            ),
            performance = listOf("swolf", "pace_100"),
            recovery = listOf("hrv", "sleep"),
            risk = listOf("shoulder_load"),
            wearables = setOf(WearableCapability.SWIM, WearableCapability.HEART_RATE, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.ENDURANCE, TrainingType.INTERVAL, TrainingType.TECHNIQUE),
            competition = setOf(CompetitionType.RACE, CompetitionType.TIME_TRIAL),
        ),
        sport(
            id = SportId.FOOTBALL,
            name = "Football",
            category = SportCategory.TEAM,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.OUTDOOR,
            part = ParticipationKind.TEAM,
            strava = "Soccer",
            equipment = listOf("Ball", "Boots"),
            required = listOf(m("distance", "Distance", "km", MetricValueType.DISTANCE), m("sprints", "Sprint Count", "count", MetricValueType.COUNT)),
            optional = listOf(m("heatmap", "Heatmap density", "", MetricValueType.SCORE), m("player_load", "Player Load", "")),
            performance = listOf("sprints", "distance"),
            recovery = listOf("hrv", "muscle_soreness"),
            risk = listOf("soft_tissue", "fixture_congestion"),
            wearables = setOf(WearableCapability.GPS, WearableCapability.HEART_RATE, WearableCapability.WEAR_OS),
            training = setOf(TrainingType.SKILL, TrainingType.INTERVAL, TrainingType.STRENGTH),
            competition = setOf(CompetitionType.MATCH, CompetitionType.LEAGUE, CompetitionType.TOURNAMENT),
        ),
        sport(
            id = SportId.BASKETBALL,
            name = "Basketball",
            category = SportCategory.TEAM,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.INDOOR,
            part = ParticipationKind.TEAM,
            strava = "Basketball",
            equipment = listOf("Ball", "Court shoes"),
            required = listOf(m("jumps", "Jumps", "count", MetricValueType.COUNT), m("load", "Player Load", "")),
            optional = listOf(m("distance", "Distance", "km")),
            performance = listOf("jumps", "load"),
            recovery = listOf("sleep", "hrv"),
            risk = listOf("ankle", "fatigue"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.STEPS, WearableCapability.WEAR_OS),
            training = setOf(TrainingType.SKILL, TrainingType.STRENGTH, TrainingType.INTERVAL),
            competition = setOf(CompetitionType.MATCH, CompetitionType.LEAGUE, CompetitionType.TOURNAMENT),
        ),
        sport(
            id = SportId.CROSSFIT,
            name = "CrossFit",
            category = SportCategory.HYBRID,
            olympic = OlympicStatus.NON_OLYMPIC,
            env = EnvironmentKind.INDOOR,
            part = ParticipationKind.BOTH,
            strava = "Crossfit",
            equipment = listOf("Barbell", "Box", "Rower"),
            required = listOf(m("wod_time", "WOD Time", "min", MetricValueType.DURATION), m("volume", "Volume", "kg")),
            optional = listOf(m("rounds", "Rounds", "count", MetricValueType.COUNT)),
            performance = listOf("wod_time", "volume"),
            recovery = listOf("hrv", "soreness"),
            risk = listOf("rhabdo_risk", "form_breakdown"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.STRENGTH, TrainingType.INTERVAL, TrainingType.MIXED),
            competition = setOf(CompetitionType.PERSONAL_CHALLENGE, CompetitionType.TOURNAMENT),
        ),
        sport(
            id = SportId.TENNIS,
            name = "Tennis",
            category = SportCategory.RACKET,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Tennis",
            equipment = listOf("Racket", "Balls"),
            required = listOf(m("rally", "Rally length", "s"), m("load", "Session load", "")),
            optional = listOf(m("hr_avg", "Avg HR", "bpm")),
            performance = listOf("rally", "load"),
            recovery = listOf("sleep", "hrv"),
            risk = listOf("shoulder", "elbow"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.GPS),
            training = setOf(TrainingType.SKILL, TrainingType.INTERVAL, TrainingType.STRENGTH),
            competition = setOf(CompetitionType.MATCH, CompetitionType.TOURNAMENT),
        ),
        sport(
            id = SportId.PADEL,
            name = "Padel",
            category = SportCategory.RACKET,
            olympic = OlympicStatus.EMERGING,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.TEAM,
            strava = "Padel",
            equipment = listOf("Padel racket", "Balls"),
            required = listOf(m("load", "Session load", ""), m("hr_avg", "Avg HR", "bpm")),
            optional = listOf(m("distance", "Distance", "km")),
            performance = listOf("load"),
            recovery = listOf("hrv"),
            risk = listOf("ankle", "elbow"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.WEAR_OS),
            training = setOf(TrainingType.SKILL, TrainingType.INTERVAL),
            competition = setOf(CompetitionType.MATCH, CompetitionType.LEAGUE, CompetitionType.TOURNAMENT),
        ),
        sport(
            id = SportId.TRIATHLON,
            name = "Triathlon",
            category = SportCategory.ENDURANCE,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Workout",
            equipment = listOf("Bike", "Wetsuit", "Shoes"),
            required = listOf(m("tss", "TSS", ""), m("brick", "Brick readiness", "", MetricValueType.SCORE)),
            optional = listOf(m("ftp", "FTP", "W"), m("pace", "Run pace", "min/km"), m("swolf", "SWOLF", "")),
            performance = listOf("tss", "brick"),
            recovery = listOf("hrv", "sleep"),
            risk = listOf("acwr", "overreaching"),
            wearables = setOf(WearableCapability.GPS, WearableCapability.POWER, WearableCapability.SWIM, WearableCapability.HEART_RATE, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.ENDURANCE, TrainingType.INTERVAL, TrainingType.COMPETITION_PREP),
            competition = setOf(CompetitionType.RACE, CompetitionType.PERSONAL_CHALLENGE),
            deps = setOf(SportId.RUNNING, SportId.CYCLING, SportId.SWIMMING),
            capabilities = setOf("multi_discipline", "brick"),
        ),
        sport(
            id = SportId.GYM,
            name = "Gym",
            category = SportCategory.STRENGTH,
            olympic = OlympicStatus.NON_OLYMPIC,
            env = EnvironmentKind.INDOOR,
            part = ParticipationKind.INDIVIDUAL,
            strava = "WeightTraining",
            equipment = listOf("Barbell", "Dumbbells", "Machines"),
            required = listOf(
                m("volume", "Volume Load", "kg"),
                m("sets", "Sets", "count", MetricValueType.COUNT),
                m("reps", "Repetitions", "count", MetricValueType.COUNT),
            ),
            optional = listOf(m("1rm", "One Rep Max", "kg"), m("rpe", "RPE", "", MetricValueType.SCORE)),
            performance = listOf("volume", "1rm"),
            recovery = listOf("soreness", "sleep"),
            risk = listOf("form_breakdown", "fatigue"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.STRENGTH, TrainingType.MOBILITY, TrainingType.RECOVERY),
            competition = setOf(CompetitionType.PERSONAL_CHALLENGE),
        ),
        sport(
            id = SportId.OTHER,
            name = "Other",
            category = SportCategory.OTHER,
            olympic = OlympicStatus.NON_OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.BOTH,
            strava = "Workout",
            equipment = emptyList(),
            required = listOf(m("duration", "Duration", "min", MetricValueType.DURATION)),
            optional = emptyList(),
            performance = listOf("duration"),
            recovery = listOf("hrv"),
            risk = listOf("fatigue"),
            wearables = setOf(WearableCapability.HEALTH_CONNECT, WearableCapability.WEAR_OS),
            training = setOf(TrainingType.MIXED),
            competition = setOf(CompetitionType.PERSONAL_CHALLENGE),
            capabilities = setOf("fallback"),
        ),
        // Extensibility examples — future sports without core changes
        sport(
            id = SportId.of("yoga"),
            name = "Yoga",
            category = SportCategory.MIND_BODY,
            olympic = OlympicStatus.NON_OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.INDIVIDUAL,
            strava = "Yoga",
            equipment = listOf("Mat"),
            required = listOf(m("duration", "Duration", "min", MetricValueType.DURATION)),
            optional = listOf(m("breath_rate", "Breath rate", "brpm")),
            performance = listOf("consistency"),
            recovery = listOf("hrv", "sleep"),
            risk = emptyList(),
            wearables = setOf(WearableCapability.HRV, WearableCapability.HEALTH_CONNECT),
            training = setOf(TrainingType.MOBILITY, TrainingType.RECOVERY),
            competition = setOf(CompetitionType.PERSONAL_CHALLENGE),
        ),
        sport(
            id = SportId.of("rowing"),
            name = "Rowing",
            category = SportCategory.ENDURANCE,
            olympic = OlympicStatus.OLYMPIC,
            env = EnvironmentKind.BOTH,
            part = ParticipationKind.BOTH,
            strava = "Rowing",
            equipment = listOf("Erg", "Boat"),
            required = listOf(m("pace_500", "Pace /500m", "min"), m("power", "Power", "W")),
            optional = listOf(m("stroke_rate", "Stroke Rate", "spm")),
            performance = listOf("pace_500", "power"),
            recovery = listOf("hrv"),
            risk = listOf("lumbar_load"),
            wearables = setOf(WearableCapability.HEART_RATE, WearableCapability.POWER),
            training = setOf(TrainingType.ENDURANCE, TrainingType.INTERVAL),
            competition = setOf(CompetitionType.RACE, CompetitionType.TIME_TRIAL),
        ),
    )

    private fun m(
        key: String,
        label: String,
        unit: String,
        type: MetricValueType = MetricValueType.NUMBER,
        kind: MetricKind = MetricKind.OPTIONAL,
    ) = MetricDefinition(key, label, unit, kind, type)

    private fun sport(
        id: SportId,
        name: String,
        category: SportCategory,
        olympic: OlympicStatus,
        env: EnvironmentKind,
        part: ParticipationKind,
        strava: String?,
        equipment: List<String>,
        required: List<MetricDefinition>,
        optional: List<MetricDefinition>,
        performance: List<String>,
        recovery: List<String>,
        risk: List<String>,
        wearables: Set<WearableCapability>,
        training: Set<TrainingType>,
        competition: Set<CompetitionType>,
        deps: Set<SportId> = emptySet(),
        capabilities: Set<String> = setOf("metrics", "training", "competition"),
    ): SportDefinition = SportDefinition(
        id = id,
        displayName = name,
        category = category,
        olympicStatus = olympic,
        environment = env,
        participation = part,
        seasonality = Seasonality.YEAR_ROUND,
        skillLevels = setOf(SkillLevel.ALL),
        equipment = equipment,
        requiredMetrics = required.map { it.copy(kind = MetricKind.REQUIRED) },
        optionalMetrics = optional.map { it.copy(kind = MetricKind.OPTIONAL) },
        performanceIndicators = performance,
        recoveryIndicators = recovery,
        riskIndicators = risk,
        supportedWearables = wearables,
        trainingTypes = training,
        competitionTypes = competition,
        stravaType = strava,
        version = 1,
        capabilities = capabilities,
        dependencies = deps,
    )
}
