// GENERATED by scripts/generate-kotlin-tokens.mjs -- do not edit. Run: pnpm tokens:kotlin
package com.fitconnect.android.design

/**
 * Elite Surface tokens (ADR-007) -- single source mirrored from
 * packages/design-tokens. Mapping to Compose Color/Dp/TextStyle happens in :design-ui.
 */
object EliteSurfaceColors {
    const val ALERT: Long = 0xFFFF3A5CL
    const val CARBON: Long = 0xFF111827L
    const val CONNECT: Long = 0xFF00DDB4L
    const val CONNECT_DIM: Long = 0x1A00DDB4L
    const val CYAN: Long = 0xFF00BFFFL
    const val ELEVATED: Long = 0xFF151B2DL
    const val FLOOR: Long = 0xFF070B14L
    const val INSTRUMENT_BEZEL: Long = 0xFF161A22L
    const val INSTRUMENT_FACE: Long = 0xFF0A0E15L
    const val INSTRUMENT_GROOVE: Long = 0xFF05070BL
    const val INSTRUMENT_MUTED: Long = 0xFF8A93A0L
    const val INSTRUMENT_TRACK: Long = 0xFF1A2028L
    const val IRIS: Long = 0xFF6C63FFL
    const val IRIS_GLOW: Long = 0x596C63FFL
    const val IRIS_SOFT: Long = 0xFFC4C0FFL
    const val LIGHT_FLOOR: Long = 0xFFE4E1EEL
    const val LIGHT_ON_SURFACE: Long = 0xFF070B14L
    const val LIGHT_ON_SURFACE_MUTED: Long = 0xFF111827L
    const val LIGHT_SURFACE: Long = 0xFFF3F1F8L
    const val LIGHT_SURFACE_CONTAINER: Long = 0xFFD8D4E6L
    const val ON_PATENT_AMBER: Long = 0xFF241700L
    const val ON_PATENT_CYAN: Long = 0xFF04222BL
    const val ON_PATENT_LEGEND: Long = 0xFF1B0729L
    const val ON_PATENT_MINT: Long = 0xFF04241AL
    const val ON_PATENT_STEEL: Long = 0xFF14191FL
    const val ON_SURFACE: Long = 0xFFE4E1EEL
    const val ON_SURFACE_MUTED: Long = 0xFFC7C4D8L
    const val ON_SURFACE_SUBTLE: Long = 0x85E4E1EEL
    const val ON_VOLT: Long = 0xFF0F1400L
    const val PATENT_EMBER: Long = 0xFFFF8A3DL
    const val PATENT_LEGEND: Long = 0xFFB44BFFL
    const val PATENT_MINT: Long = 0xFF2FE3A0L
    const val PATENT_STEEL: Long = 0xFF7A8899L
    const val PERFORMANCE: Long = 0xFF00E090L
    const val RECOVERY: Long = 0xFFFFB020L
    const val SURFACE: Long = 0xFF13121BL
    const val SURFACE_CONTAINER: Long = 0xFF1F1F28L
    const val SURFACE_CONTAINER_HIGH: Long = 0xFF2A2933L
    const val SURFACE_CONTAINER_HIGHEST: Long = 0xFF35343EL
    const val TELEMETRY: Long = 0xFF3CD7FFL
    const val TELEMETRY_DIM: Long = 0x1F3CD7FFL
    const val VOLT_300: Long = 0xFFD4FF4DL
    const val VOLT_400: Long = 0xFFD0FF33L
    const val VOLT_600: Long = 0xFFA8D700L
    const val VOLTLINE: Long = 0xFFC8FF00L
    const val VOLTLINE_DIM: Long = 0x1FC8FF00L
    const val VOLTLINE_GLOW: Long = 0x66C8FF00L
}

object EliteSurfaceSpacing {
    const val NONE: Int = 0
    const val XXS: Int = 2
    const val XS: Int = 4
    const val SM: Int = 8
    const val MD: Int = 12
    const val LG: Int = 16
    const val INSET: Int = 20
    const val XL: Int = 24
    const val XXL: Int = 32
    const val SECTION: Int = 40
    const val XXXL: Int = 48
    const val HUGE: Int = 64
}

object EliteSurfaceRadius {
    const val NONE: Int = 0
    const val XS: Int = 4
    const val SM: Int = 8
    const val MD: Int = 12
    const val LG: Int = 16
    const val XL: Int = 24
    const val FULL: Int = 999
}

object EliteSurfaceElevation {
    const val NONE: Int = 0
    const val LOW: Int = 1
    const val MID: Int = 3
    const val HIGH: Int = 6
    const val OVERLAY: Int = 12
}

object EliteSurfaceOpacity {
    const val DISABLED: Float = 0.38f
    const val MUTED: Float = 0.52f
    const val SUBTLE: Float = 0.72f
    const val GLASS: Float = 0.72f
    const val SCRIM: Float = 0.56f
    const val BORDER: Float = 0.16f
}

object EliteSurfaceBorder {
    const val HAIRLINE: Float = 1f
    const val THIN: Float = 1.5f
    const val THICK: Float = 2f
}

object EliteSurfaceGlass {
    const val L_1: Float = 0.88f
    const val L_2: Float = 0.72f
    const val L_3: Float = 0.64f
    const val L_4: Float = 0.52f
    const val L_5: Float = 0.42f
    const val HIGHLIGHT: Float = 0.18f
    const val BLUR_L_3: Int = 8
    const val BLUR_L_4: Int = 12
    const val BLUR_L_5: Int = 20
}

object EliteSurfaceAtmosphere {
    const val HONEYCOMB_SUBTLE: Float = 0.06f
    const val HONEYCOMB_EMPTY: Float = 0.16f
    const val HONEYCOMB_PARALLAX: Float = 0.04f
    const val HONEYCOMB_PULSE: Float = 0.12f
    const val HONEYCOMB_CELL_RADIUS: Int = 28
    const val HONEYCOMB_DRIFT_MS: Int = 32000
    const val HONEYCOMB_MAX_CELLS: Int = 120
    const val HONEYCOMB_PULSE_CELLS: Int = 3
    const val HONEYCOMB_COVERAGE: Float = 0.58f
    const val HONEYCOMB_BUDGET_MS: Float = 1.5f
    const val HONEYCOMB_SESSION_SCALE: Float = 0.3f
}

object EliteSurfaceInstrument {
    const val BEZEL: Float = 0.085f
    const val GROOVE: Float = 0.045f
    const val HALO: Float = 0.065f
    const val STROKE: Float = 0.031f
    const val SPECULAR: Float = 0.027f
    const val TRACK_RADIUS: Float = 0.405f
    const val HALO_ALPHA: Float = 0.18f
    const val SPECULAR_ALPHA: Float = 0.05f
    const val HERO_DP: Int = 224
    const val PROFILE_DP: Int = 160
    const val INLINE_DP: Int = 88
    const val LOAD_TIMEOUT_MS: Int = 8000
    const val HEADER_DP: Int = 52
    const val HEXATAR_HEADER_DP: Int = 32
    const val HEXATAR_PROFILE_DP: Int = 104
    const val HEXATAR_FEED_DP: Int = 26
    const val HEXATAR_BADGE_DP: Int = 14
    const val LOGO_MARK_DP: Int = 24
}

object EliteSurfaceMotion {
    const val MICRO_MS: Int = 150
    const val UI_MS: Int = 220
    const val SCREEN_MS: Int = 400
    const val DATA_MS: Int = 1200
}

object EliteSurfaceType {
    const val DISPLAY_XL_SIZE_SP: Float = 40f
    const val DISPLAY_XL_LINE_HEIGHT_SP: Float = 44f
    const val DISPLAY_XL_WEIGHT: Int = 700
    const val DISPLAY_XL_TRACKING: Float = -0.8f
    const val DISPLAY_XL_FAMILY: String = "display"
    const val DISPLAY_L_SIZE_SP: Float = 32f
    const val DISPLAY_L_LINE_HEIGHT_SP: Float = 36f
    const val DISPLAY_L_WEIGHT: Int = 700
    const val DISPLAY_L_TRACKING: Float = -0.6f
    const val DISPLAY_L_FAMILY: String = "display"
    const val HEADLINE_SIZE_SP: Float = 24f
    const val HEADLINE_LINE_HEIGHT_SP: Float = 30f
    const val HEADLINE_WEIGHT: Int = 700
    const val HEADLINE_TRACKING: Float = -0.4f
    const val HEADLINE_FAMILY: String = "display"
    const val TITLE_SIZE_SP: Float = 20f
    const val TITLE_LINE_HEIGHT_SP: Float = 26f
    const val TITLE_WEIGHT: Int = 600
    const val TITLE_TRACKING: Float = -0.2f
    const val TITLE_FAMILY: String = "body"
    const val SUBTITLE_SIZE_SP: Float = 16f
    const val SUBTITLE_LINE_HEIGHT_SP: Float = 22f
    const val SUBTITLE_WEIGHT: Int = 600
    const val SUBTITLE_TRACKING: Float = 0f
    const val SUBTITLE_FAMILY: String = "body"
    const val BODY_SIZE_SP: Float = 15f
    const val BODY_LINE_HEIGHT_SP: Float = 22f
    const val BODY_WEIGHT: Int = 400
    const val BODY_TRACKING: Float = 0f
    const val BODY_FAMILY: String = "body"
    const val CAPTION_SIZE_SP: Float = 12f
    const val CAPTION_LINE_HEIGHT_SP: Float = 16f
    const val CAPTION_WEIGHT: Int = 500
    const val CAPTION_TRACKING: Float = 0.2f
    const val CAPTION_FAMILY: String = "body"
    const val OVERLINE_SIZE_SP: Float = 11f
    const val OVERLINE_LINE_HEIGHT_SP: Float = 14f
    const val OVERLINE_WEIGHT: Int = 600
    const val OVERLINE_TRACKING: Float = 1.2f
    const val OVERLINE_FAMILY: String = "body"
    const val METRIC_SIZE_SP: Float = 28f
    const val METRIC_LINE_HEIGHT_SP: Float = 32f
    const val METRIC_WEIGHT: Int = 300
    const val METRIC_TRACKING: Float = -0.4f
    const val METRIC_FAMILY: String = "mono"
    const val METRIC_HERO_SIZE_SP: Float = 52f
    const val METRIC_HERO_LINE_HEIGHT_SP: Float = 52f
    const val METRIC_HERO_WEIGHT: Int = 300
    const val METRIC_HERO_TRACKING: Float = -1.2f
    const val METRIC_HERO_FAMILY: String = "body"
    const val MONOSPACE_SIZE_SP: Float = 13f
    const val MONOSPACE_LINE_HEIGHT_SP: Float = 18f
    const val MONOSPACE_WEIGHT: Int = 500
    const val MONOSPACE_TRACKING: Float = 0f
    const val MONOSPACE_FAMILY: String = "mono"
}

object EliteSurfaceSemantic {
    const val SUCCESS: Long = 0xFF00E090L
    const val WARNING: Long = 0xFFFFB020L
    const val DANGER: Long = 0xFFFF3A5CL
    const val INFO: Long = 0xFF3CD7FFL
    const val FOCUS: Long = 0xFF6C63FFL
    const val CTA: Long = 0xFFC8FF00L
    const val TRUST: Long = 0xFF00DDB4L
}

object EliteSurfaceCharts {
    const val HRV: Long = 0xFF00DDB4L
    const val HEART_RATE: Long = 0xFFFF3A5CL
    const val READINESS: Long = 0xFFC8FF00L
    const val SLEEP: Long = 0xFF6C63FFL
    const val RECOVERY: Long = 0xFFFFB020L
    const val PERFORMANCE: Long = 0xFF00E090L
    const val TRAINING_LOAD: Long = 0xFF3CD7FFL
    const val WEIGHT: Long = 0xFFC7C4D8L
    const val HYDRATION: Long = 0xFF00BFFFL
}
