// GENERATED by scripts/generate-kotlin-tokens.mjs — do not edit. Run: pnpm tokens:kotlin
package com.fitconnect.android.design

/**
 * Elite Surface colour tokens (ADR-007), mirrored from
 * packages/design-tokens COLOR_TOKENS. ARGB Long values, zero dependencies —
 * mapping to androidx.compose.ui.graphics.Color happens at the theme layer.
 */
object EliteSurfaceColors {
    const val ALERT: Long = 0xFFFF3A5CL
    const val CARBON: Long = 0xFF111827L
    const val CONNECT: Long = 0xFF00DDB4L
    const val CONNECT_DIM: Long = 0x1A00DDB4L
    const val CYAN: Long = 0xFF00BFFFL
    const val ELEVATED: Long = 0xFF151B2DL
    const val FLOOR: Long = 0xFF070B14L
    const val IRIS: Long = 0xFF6C63FFL
    const val IRIS_GLOW: Long = 0x596C63FFL
    const val IRIS_SOFT: Long = 0xFFC4C0FFL
    const val ON_SURFACE: Long = 0xFFE4E1EEL
    const val ON_SURFACE_MUTED: Long = 0xFFC7C4D8L
    const val ON_SURFACE_SUBTLE: Long = 0x85E4E1EEL
    const val PERFORMANCE: Long = 0xFF00E090L
    const val RECOVERY: Long = 0xFFFFB020L
    const val SURFACE: Long = 0xFF13121BL
    const val SURFACE_CONTAINER: Long = 0xFF1F1F28L
    const val SURFACE_CONTAINER_HIGH: Long = 0xFF2A2933L
    const val SURFACE_CONTAINER_HIGHEST: Long = 0xFF35343EL
    const val TELEMETRY: Long = 0xFF3CD7FFL
    const val TELEMETRY_DIM: Long = 0x1F3CD7FFL
    const val VOLTLINE: Long = 0xFFC8FF00L
    const val VOLTLINE_DIM: Long = 0x1FC8FF00L
    const val VOLTLINE_GLOW: Long = 0x66C8FF00L
    const val VOLT_300: Long = 0xFFD4FF4DL
    const val VOLT_400: Long = 0xFFD0FF33L
    const val VOLT_600: Long = 0xFFA8D700L
}
