// GENERATED by scripts/generate-kotlin-tokens.mjs -- do not edit. Run: pnpm tokens:kotlin
package com.fitconnect.android.design

/**
 * Elite Surface tokens (ADR-007) -- single source mirrored from
 * packages/design-tokens. Mapping to Compose Color/Dp/TextStyle happens in :design-ui.
 */
object EliteSurfaceColors {
    const val ALERT: Long = 0xFFFF3A5CL
    const val CARBON: Long = 0xFF111827L
    const val CONNECT: Long = 0xFF00DDB4L
    const val CONNECT_DIM: Long = 0x1A00DDB4L
    const val CYAN: Long = 0xFF00BFFFL
    const val ELEVATED: Long = 0xFF151B2DL
    const val FLOOR: Long = 0xFF070B14L
    const val IRIS: Long = 0xFF6C63FFL
    const val IRIS_GLOW: Long = 0x596C63FFL
    const val IRIS_SOFT: Long = 0xFFC4C0FFL
    const val LIGHT_FLOOR: Long = 0xFFE4E1EEL
    const val LIGHT_ON_SURFACE: Long = 0xFF070B14L
    const val LIGHT_ON_SURFACE_MUTED: Long = 0xFF111827L
    const val LIGHT_SURFACE: Long = 0xFFF3F1F8L
    const val LIGHT_SURFACE_CONTAINER: Long = 0xFFD8D4E6L
    const val ON_SURFACE: Long = 0xFFE4E1EEL
    const val ON_SURFACE_MUTED: Long = 0xFFC7C4D8L
    const val ON_SURFACE_SUBTLE: Long = 0x85E4E1EEL
    const val PERFORMANCE: Long = 0xFF00E090L
    const val RECOVERY: Long = 0xFFFFB020L
    const val SURFACE: Long = 0xFF13121BL
    const val SURFACE_CONTAINER: Long = 0xFF1F1F28L
    const val SURFACE_CONTAINER_HIGH: Long = 0xFF2A2933L
    const val SURFACE_CONTAINER_HIGHEST: Long = 0xFF35343EL
    const val TELEMETRY: Long = 0xFF3CD7FFL
    const val TELEMETRY_DIM: Long = 0x1F3CD7FFL
    const val VOLT_300: Long = 0xFFD4FF4DL
    const val VOLT_400: Long = 0xFFD0FF33L
    const val VOLT_600: Long = 0xFFA8D700L
    const val VOLTLINE: Long = 0xFFC8FF00L
    const val VOLTLINE_DIM: Long = 0x1FC8FF00L
    const val VOLTLINE_GLOW: Long = 0x66C8FF00L
}

object EliteSurfaceSpacing {
    const val NONE: Int = 0
    const val XXS: Int = 2
    const val XS: Int = 4
    const val SM: Int = 8
    const val MD: Int = 12
    const val LG: Int = 16
    const val XL: Int = 24
    const val XXL: Int = 32
    const val XXXL: Int = 48
    const val HUGE: Int = 64
}

object EliteSurfaceRadius {
    const val NONE: Int = 0
    const val XS: Int = 4
    const val SM: Int = 8
    const val MD: Int = 12
    const val LG: Int = 16
    const val XL: Int = 24
    const val FULL: Int = 999
}

object EliteSurfaceElevation {
    const val NONE: Int = 0
    const val LOW: Int = 1
    const val MID: Int = 3
    const val HIGH: Int = 6
    const val OVERLAY: Int = 12
}

object EliteSurfaceOpacity {
    const val DISABLED: Float = 0.38f
    const val MUTED: Float = 0.52f
    const val SUBTLE: Float = 0.72f
    const val GLASS: Float = 0.72f
    const val SCRIM: Float = 0.56f
    const val BORDER: Float = 0.16f
}

object EliteSurfaceBorder {
    const val HAIRLINE: Float = 1f
    const val THIN: Float = 1.5f
    const val THICK: Float = 2f
}

object EliteSurfaceMotion {
    const val MICRO_MS: Int = 150
    const val UI_MS: Int = 220
    const val SCREEN_MS: Int = 400
    const val DATA_MS: Int = 1200
}

object EliteSurfaceType {
    const val DISPLAY_XL_SIZE_SP: Float = 40f
    const val DISPLAY_XL_LINE_HEIGHT_SP: Float = 44f
    const val DISPLAY_XL_WEIGHT: Int = 700
    const val DISPLAY_XL_TRACKING: Float = -0.8f
    const val DISPLAY_XL_FAMILY: String = "display"
    const val DISPLAY_L_SIZE_SP: Float = 32f
    const val DISPLAY_L_LINE_HEIGHT_SP: Float = 36f
    const val DISPLAY_L_WEIGHT: Int = 700
    const val DISPLAY_L_TRACKING: Float = -0.6f
    const val DISPLAY_L_FAMILY: String = "display"
    const val HEADLINE_SIZE_SP: Float = 24f
    const val HEADLINE_LINE_HEIGHT_SP: Float = 30f
    const val HEADLINE_WEIGHT: Int = 700
    const val HEADLINE_TRACKING: Float = -0.4f
    const val HEADLINE_FAMILY: String = "display"
    const val TITLE_SIZE_SP: Float = 20f
    const val TITLE_LINE_HEIGHT_SP: Float = 26f
    const val TITLE_WEIGHT: Int = 600
    const val TITLE_TRACKING: Float = -0.2f
    const val TITLE_FAMILY: String = "body"
    const val SUBTITLE_SIZE_SP: Float = 16f
    const val SUBTITLE_LINE_HEIGHT_SP: Float = 22f
    const val SUBTITLE_WEIGHT: Int = 600
    const val SUBTITLE_TRACKING: Float = 0f
    const val SUBTITLE_FAMILY: String = "body"
    const val BODY_SIZE_SP: Float = 15f
    const val BODY_LINE_HEIGHT_SP: Float = 22f
    const val BODY_WEIGHT: Int = 400
    const val BODY_TRACKING: Float = 0f
    const val BODY_FAMILY: String = "body"
    const val CAPTION_SIZE_SP: Float = 12f
    const val CAPTION_LINE_HEIGHT_SP: Float = 16f
    const val CAPTION_WEIGHT: Int = 500
    const val CAPTION_TRACKING: Float = 0.2f
    const val CAPTION_FAMILY: String = "body"
    const val OVERLINE_SIZE_SP: Float = 11f
    const val OVERLINE_LINE_HEIGHT_SP: Float = 14f
    const val OVERLINE_WEIGHT: Int = 600
    const val OVERLINE_TRACKING: Float = 1.2f
    const val OVERLINE_FAMILY: String = "body"
    const val METRIC_SIZE_SP: Float = 28f
    const val METRIC_LINE_HEIGHT_SP: Float = 32f
    const val METRIC_WEIGHT: Int = 600
    const val METRIC_TRACKING: Float = -0.4f
    const val METRIC_FAMILY: String = "mono"
    const val MONOSPACE_SIZE_SP: Float = 13f
    const val MONOSPACE_LINE_HEIGHT_SP: Float = 18f
    const val MONOSPACE_WEIGHT: Int = 500
    const val MONOSPACE_TRACKING: Float = 0f
    const val MONOSPACE_FAMILY: String = "mono"
}

object EliteSurfaceSemantic {
    const val SUCCESS: Long = 0xFF00E090L
    const val WARNING: Long = 0xFFFFB020L
    const val DANGER: Long = 0xFFFF3A5CL
    const val INFO: Long = 0xFF3CD7FFL
    const val FOCUS: Long = 0xFF6C63FFL
    const val CTA: Long = 0xFFC8FF00L
    const val TRUST: Long = 0xFF00DDB4L
}

object EliteSurfaceCharts {
    const val HRV: Long = 0xFF00DDB4L
    const val HEART_RATE: Long = 0xFFFF3A5CL
    const val READINESS: Long = 0xFFC8FF00L
    const val SLEEP: Long = 0xFF6C63FFL
    const val RECOVERY: Long = 0xFFFFB020L
    const val PERFORMANCE: Long = 0xFF00E090L
    const val TRAINING_LOAD: Long = 0xFF3CD7FFL
    const val WEIGHT: Long = 0xFFC7C4D8L
    const val HYDRATION: Long = 0xFF00BFFFL
}
