package com.fitconnect.ascend.copy

object AscendCopy {
    fun t(locale: String, key: String, args: Map<String, String> = emptyMap()): String {
        val table = if (locale.startsWith("pt", ignoreCase = true)) PT else EN
        var value = table[key] ?: EN[key] ?: key
        args.forEach { (k, v) -> value = value.replace("{$k}", v) }
        return value
    }

    private val EN = mapOf(
        "rank.initiate" to "INITIATE",
        "rank.activated" to "ACTIVATED",
        "rank.mover" to "MOVER",
        "rank.athlete" to "ATHLETE",
        "rank.performer" to "PERFORMER",
        "rank.competitor" to "COMPETITOR",
        "rank.elite" to "ELITE",
        "rank.advanced_elite" to "ADVANCED ELITE",
        "rank.performance_pro" to "PERFORMANCE PRO",
        "rank.high_performance" to "HIGH PERFORMANCE",
        "rank.prime" to "PRIME",
        "rank.elite_prime" to "ELITE PRIME",
        "rank.ascendant" to "ASCENDANT",
        "rank.apex" to "APEX",
        "rank.legacy" to "LEGACY",
        "title.daily_runner" to "DAILY RUNNER",
        "title.consistency_beast" to "CONSISTENCY BEAST",
        "title.unbreakable" to "UNBREAKABLE",
        "title.iron_mind" to "IRON MIND",
        "title.road_warrior" to "ROAD WARRIOR",
        "title.marathoner" to "MARATHONER",
        "title.recovery_master" to "RECOVERY MASTER",
        "title.pace_machine" to "PACE MACHINE",
        "title.ultra_runner" to "ULTRA RUNNER",
        "title.clutch" to "CLUTCH PERFORMER",
        "title.elite_athlete" to "ELITE ATHLETE",
        "unlock.map_themes" to "Map themes",
        "unlock.performance_radar" to "Performance Radar",
        "unlock.advanced_analytics" to "Advanced analytics",
        "unlock.advanced_challenges" to "Advanced challenges",
        "unlock.ai_reports" to "AI reports",
        "unlock.achievement_frames" to "Achievement frames",
        "xp.activity.session" to "Session load — activity",
        "xp.activity.recovery_weighted" to "Recovery-weighted activity — extra volume is not rewarded",
        "xp.quality.session" to "Performance quality",
        "xp.activity.distance" to "Distance completed",
        "xp.goals.completed" to "Goal completed",
        "xp.consistency.daily" to "Daily target",
        "xp.consistency.weekly" to "Weekly protocol",
        "xp.consistency.monthly" to "Monthly ascension",
        "xp.records.new" to "Personal record",
        "xp.recovery.target" to "Recovery protocol",
        "xp.sleep.target" to "Sleep target",
        "xp.recovery.sleep" to "Sleep supporting recovery",
        "xp.coach.plan" to "Coach plan",
        "xp.consistency.milestone" to "Consistency milestone",
        "xp.community.action" to "Community action",
        "xp.challenge.completed" to "Challenge complete",
        "xp.map.milestone" to "Map milestone",
        "xp.skill.first" to "First activity",
        "xp.skill.sport" to "New sport",
        "xp.skill.route" to "New route",
        "xp.activity.elevation" to "Elevation milestone",
        "ach.first_km" to "First kilometer",
        "ach.first_km.d" to "Your performance profile recorded its first kilometer.",
        "ach.club_10" to "10 KM Club",
        "ach.club_10.d" to "Ten kilometers of recorded movement.",
        "ach.club_50" to "50 KM Club",
        "ach.club_50.d" to "Fifty kilometers accumulated.",
        "ach.club_100" to "100 KM Club",
        "ach.club_100.d" to "One hundred kilometers accumulated.",
        "ach.club_500" to "500 KM Club",
        "ach.club_500.d" to "Five hundred kilometers accumulated.",
        "ach.club_1000" to "1,000 KM Club",
        "ach.club_1000.d" to "One thousand kilometers accumulated.",
        "ach.club_5000" to "5,000 KM Legacy",
        "ach.club_5000.d" to "Five thousand kilometers — a long game.",
        "ach.daily_runner" to "Daily runner",
        "ach.daily_runner.d" to "Three consecutive training days.",
        "ach.consistency_engine" to "Consistency engine",
        "ach.consistency_engine.d" to "Seven-day performance streak, recovery-aware.",
        "ach.unbreakable" to "Unbreakable",
        "ach.unbreakable.d" to "Fourteen-day performance streak.",
        "ach.iron_routine" to "Iron routine",
        "ach.iron_routine.d" to "Thirty-day performance streak.",
        "ach.legacy_athlete" to "Legacy athlete",
        "ach.legacy_athlete.d" to "One hundred days of intelligent consistency.",
        "ach.cardio_initiate" to "Cardio initiate",
        "ach.cardio_initiate.d" to "First cardio session recorded.",
        "ach.aerobic_engine" to "Aerobic engine",
        "ach.aerobic_engine.d" to "Twelve cardio sessions.",
        "ach.first_pr" to "First PR",
        "ach.first_pr.d" to "A personal record entered the vault.",
        "ach.pace_breaker" to "Pace breaker",
        "ach.pace_breaker.d" to "Three personal records.",
        "ach.endurance_10k" to "10K engine",
        "ach.endurance_10k.d" to "A single activity of 10 km or more.",
        "ach.half_distance" to "Half distance",
        "ach.half_distance.d" to "A single activity of 21 km or more.",
        "ach.recovery_discipline" to "Recovery discipline",
        "ach.recovery_discipline.d" to "Three recovery-protocol days.",
        "ach.sleep_architect" to "Sleep architect",
        "ach.sleep_architect.d" to "Five sleep-target days.",
        "ach.prime_recovery" to "Prime recovery",
        "ach.prime_recovery.d" to "Seven recovery-protocol days.",
        "ach.first_session" to "Signal acquired",
        "ach.first_session.d" to "First recorded session — the profile exists.",
        "ach.multi_sport" to "Multi-sport",
        "ach.multi_sport.d" to "Three sports in the registry.",
        "ach.new_territory" to "New territory",
        "ach.new_territory.d" to "Two distinct routes discovered.",
        "ach.elevation_core" to "Elevation core",
        "ach.elevation_core.d" to "500 m of accumulated climbing.",
        "ach.owned.demo" to "LOCAL_DEMO · simulated rarity — not population data",
        "mission.daily.move_or_recover" to "Complete one session or a recovery protocol",
        "mission.daily.why" to "Consistency includes rest.",
        "mission.weekly.distance" to "Accumulate 20 km this week",
        "mission.weekly.why" to "Endurance builds in weekly blocks.",
        "mission.monthly.distance" to "Accumulate 80 km this month",
        "mission.monthly.why" to "Monthly volume with recovery still in the loop.",
        "mission.personal.endurance" to "Open a 10 km personal mission",
        "mission.personal.why" to "A horizon you chose.",
        "mission.coach.assigned" to "Coach-assigned protocol",
        "challenge.distance_week" to "Distance week",
        "challenge.squad_week" to "FC Performance Week",
        "energy.deployed" to "ENERGY DEPLOYED",
        "energy.chicken_thighs" to "Illustrative equivalent ≈ {n} chicken thighs",
        "energy.disclaimer" to "Illustrative energy equivalent. Not a nutritional equivalence. Not a food reward.",
        "convert.porto_matosinhos" to "You travelled approximately Porto → Matosinhos",
        "convert.porto_matosinhos.d" to "Contextual distance, not a surveyed route claim.",
        "convert.distance_km" to "Continuous movement on record",
        "convert.distance_km.d" to "Distance from the session payload.",
        "convert.floors" to "Elevation as floors",
        "convert.floors.d" to "Approximately 3 m per floor. Illustrative.",
        "convert.time" to "Continuous movement time",
        "convert.time.d" to "Elapsed moving time from the session.",
        "segment.ribeira" to "Ribeira Climb · LOCAL_DEMO",
        "dna.insufficient" to "Not enough sessions to classify an athlete type.",
        "dna.demo" to "LOCAL_DEMO DNA — calculated from demo events, not live biometrics.",
        "dna.calculated" to "Calculated from recorded sessions only.",
        "motivation.insufficient" to "Motivation profile waits for more history.",
        "motivation.competitor" to "Squad progress is a team signal — not a public ranking.",
        "motivation.achiever" to "A small set of achievements remains in the vault.",
        "motivation.explorer" to "New territory is already in your map history.",
        "motivation.consistency" to "A performance streak is active, including recovery protection.",
        "motivation.scientist" to "Recovery and sleep signals are part of your profile.",
        "ui.sys" to "SYS / ASCEND",
        "ui.performance_status" to "PERFORMANCE STATUS",
        "ui.xp_engine" to "XP ENGINE",
        "ui.next_unlock" to "NEXT UNLOCK",
        "ui.vault" to "PERFORMANCE VAULT",
        "ui.complete" to "PERFORMANCE COMPLETE",
        "ui.level_up" to "LEVEL UP",
        "ui.energy" to "ENERGY DEPLOYED",
        "ui.trace" to "PERFORMANCE TRACE",
        "ui.dna" to "ATHLETE DNA",
        "ui.directive" to "AI PERFORMANCE DIRECTIVE",
        "ui.streak" to "PERFORMANCE STREAK",
        "ui.mission" to "DAILY MISSION",
        "type.UNCLASSIFIED" to "Unclassified",
        "type.THE_ENGINE" to "THE ENGINE",
        "type.THE_SPRINTER" to "THE SPRINTER",
        "type.THE_CLIMBER" to "THE CLIMBER",
        "type.THE_DISCIPLINED" to "THE DISCIPLINED",
        "type.THE_BALANCED" to "THE BALANCED",
        "type.THE_RECOVERY_MASTER" to "THE RECOVERY MASTER",
        "type.THE_EXPLORER" to "THE EXPLORER",
    )

    private val PT = mapOf(
        "rank.initiate" to "INICIANTE",
        "rank.activated" to "ATIVADO",
        "rank.mover" to "MOVER",
        "rank.athlete" to "ATLETA",
        "rank.performer" to "PERFORMER",
        "rank.competitor" to "COMPETIDOR",
        "rank.elite" to "ELITE",
        "rank.advanced_elite" to "ELITE AVANÇADO",
        "rank.performance_pro" to "PERFORMANCE PRO",
        "rank.high_performance" to "ALTA PERFORMANCE",
        "rank.prime" to "PRIME",
        "rank.elite_prime" to "ELITE PRIME",
        "rank.ascendant" to "ASCENDANT",
        "rank.apex" to "APEX",
        "rank.legacy" to "LEGACY",
        "title.daily_runner" to "DAILY RUNNER",
        "title.consistency_beast" to "CONSISTENCY BEAST",
        "title.unbreakable" to "UNBREAKABLE",
        "title.iron_mind" to "IRON MIND",
        "title.road_warrior" to "ROAD WARRIOR",
        "title.marathoner" to "MARATHONER",
        "title.recovery_master" to "RECOVERY MASTER",
        "title.pace_machine" to "PACE MACHINE",
        "title.ultra_runner" to "ULTRA RUNNER",
        "title.clutch" to "CLUTCH PERFORMER",
        "title.elite_athlete" to "ELITE ATHLETE",
        "unlock.performance_radar" to "Performance Radar",
        "xp.activity.recovery_weighted" to "Atividade ponderada pela recuperação — volume extra não é recompensado",
        "ach.owned.demo" to "LOCAL_DEMO · raridade simulada — não é dado populacional",
        "energy.deployed" to "ENERGIA DEPLOYED",
        "energy.chicken_thighs" to "Equivalente ilustrativo ≈ {n} coxas de frango",
        "energy.disclaimer" to "Equivalente energético ilustrativo. Não é equivalência nutricional. Não é recompensa alimentar.",
        "convert.porto_matosinhos" to "Percorreste aproximadamente Porto → Matosinhos",
        "ui.sys" to "SYS / ASCEND",
        "ui.vault" to "PERFORMANCE VAULT",
        "ui.complete" to "PERFORMANCE COMPLETE",
        "ui.level_up" to "LEVEL UP",
        "ui.dna" to "ATHLETE DNA",
        "dna.insufficient" to "Ainda não há sessões suficientes para classificar o tipo de atleta.",
        "dna.demo" to "DNA LOCAL_DEMO — calculado a partir de eventos demo, não de biometria ao vivo.",
        "motivation.insufficient" to "O perfil de motivação espera por mais histórico.",
        "type.THE_ENGINE" to "THE ENGINE",
        "type.THE_SPRINTER" to "THE SPRINTER",
        "type.THE_CLIMBER" to "THE CLIMBER",
        "type.THE_DISCIPLINED" to "THE DISCIPLINED",
        "type.THE_BALANCED" to "THE BALANCED",
        "type.THE_RECOVERY_MASTER" to "THE RECOVERY MASTER",
        "type.THE_EXPLORER" to "THE EXPLORER",
        "type.UNCLASSIFIED" to "Não classificado",
    )
}
