#!/usr/bin/env node
/**
 * Check which production env vars are configured.
 * Usage: node scripts/validate-env.mjs [--env .env.local]
 */
import fs from "node:fs";
import path from "node:path";

const envPath = process.argv.includes("--env")
  ? process.argv[process.argv.indexOf("--env") + 1]
  : path.resolve(".env.local");

function parseEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const GROUPS = [
  {
    title: "Supabase (auth + DB)",
    vars: [
      { key: "NEXT_PUBLIC_SUPABASE_URL", required: true, hint: "Project Settings → API → Project URL" },
      { key: "NEXT_PUBLIC_SUPABASE_ANON_KEY", required: true, hint: "Project Settings → API → anon public" },
      { key: "SUPABASE_SERVICE_ROLE_KEY", required: true, hint: "Project Settings → API → service_role (server only)" },
      { key: "DATABASE_URL", required: true, hint: "Project Settings → Database → Connection string (pooler)" }
    ]
  },
  {
    title: "Stripe (live payments)",
    vars: [
      { key: "STRIPE_SECRET_KEY", required: true, hint: "Dashboard → Developers → API keys → Secret key" },
      { key: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", required: true, hint: "Dashboard → Developers → API keys → Publishable key" },
      { key: "STRIPE_WEBHOOK_SECRET", required: true, hint: "Webhook endpoint → signing secret (whsec_…)" }
    ]
  },
  {
    title: "Strava",
    vars: [
      { key: "STRAVA_CLIENT_ID", required: true, hint: "https://www.strava.com/settings/api" },
      { key: "STRAVA_CLIENT_SECRET", required: true, hint: "Strava API settings" },
      { key: "STRAVA_WEBHOOK_VERIFY_TOKEN", required: true, hint: "Your custom verify token (match Strava subscription)" },
      { key: "STRAVA_TOKEN_ENCRYPTION_KEY", required: true, hint: "Run: node scripts/setup-production-env.mjs" },
      { key: "STRAVA_OAUTH_STATE_SECRET", required: false, hint: "Auto-generated by setup script" }
    ]
  },
  {
    title: "Upstash (rate limit / cache)",
    vars: [
      { key: "UPSTASH_REDIS_REST_URL", required: true, hint: "Upstash console → Redis → REST URL" },
      { key: "UPSTASH_REDIS_REST_TOKEN", required: true, hint: "Upstash console → Redis → REST token" }
    ]
  },
  {
    title: "Analytics (optional but recommended)",
    vars: [
      { key: "NEXT_PUBLIC_POSTHOG_KEY", required: false, hint: "PostHog → Project → Project API Key (phc_…)" },
      { key: "NEXT_PUBLIC_SENTRY_DSN", required: false, hint: "Sentry → Project Settings → Client DSN" }
    ]
  },
  {
    title: "App mode",
    vars: [
      { key: "NEXT_PUBLIC_DEMO_MODE", required: true, hint: 'Set to "false" for production' },
      { key: "NEXT_PUBLIC_APP_URL", required: true, hint: "Production URL for Stripe/Strava callbacks" }
    ]
  }
];

const env = parseEnv(envPath);
const isSet = (key) => {
  const v = env[key]?.trim();
  return Boolean(
    v &&
      !v.includes("your-") &&
      !v.includes("PASTE_") &&
      v !== '""' &&
      v !== "''"
  );
};

console.log(`\nFitConnect env check — ${envPath}\n`);

let missingRequired = 0;
let configured = 0;

for (const group of GROUPS) {
  console.log(`── ${group.title} ──`);
  for (const { key, required, hint } of group.vars) {
    const ok = isSet(key);
    if (ok) configured += 1;
    else if (required) missingRequired += 1;
    const mark = ok ? "✓" : required ? "✗" : "○";
    console.log(`  ${mark} ${key}${ok ? "" : `\n      → ${hint}`}`);
  }
  console.log("");
}

console.log(`Configured: ${configured} · Missing required: ${missingRequired}\n`);

if (missingRequired > 0) {
  console.log("Next steps:");
  console.log("  1. Open https://supabase.com/dashboard/project/beuiammeedpovdkmhluw/settings/api");
  console.log("  2. Copy anon + service_role keys into .env.local");
  console.log("  3. Database URL: Settings → Database → Connection string (Transaction pooler)");
  console.log("  4. Stripe: https://dashboard.stripe.com/apikeys");
  console.log("  5. Strava: https://www.strava.com/settings/api");
  console.log("     Callback: {NEXT_PUBLIC_APP_URL}/api/v1/integrations/strava/callback");
  console.log("     Webhook:  {NEXT_PUBLIC_APP_URL}/api/v1/integrations/strava/webhook");
  console.log("  6. Upstash: https://console.upstash.com/");
  console.log("  7. Mirror all vars in Vercel → Project → Settings → Environment Variables\n");
  process.exit(1);
}

console.log("All required variables are set.\n");
