import type {
  CombatFamily,
  CombatMetricKey,
  CombatSessionMode,
  MartialArtDiscipline,
  PracticeKind,
  RulesetRef
} from "@fitconnect/types";

export const MARTIAL_ARTS_CATALOG_VERSION = "2026.09.1";

const STRIKE_METRICS: CombatMetricKey[] = [
  "punch_count",
  "kick_count",
  "strike_count",
  "strike_rate",
  "strike_acceleration",
  "strike_velocity",
  "work_rate",
  "rpe",
  "session_duration",
  "heart_rate"
];

const GRAPPLE_METRICS: CombatMetricKey[] = [
  "takedown_attempts",
  "takedowns",
  "control_time",
  "submission_attempts",
  "rpe",
  "session_duration",
  "heart_rate"
];

const MIXED_METRICS: CombatMetricKey[] = [...new Set([...STRIKE_METRICS, ...GRAPPLE_METRICS])];

const FORM_METRICS: CombatMetricKey[] = ["session_duration", "rpe", "work_rate"];

function ruleset(id: string, version: string, name: string, scoringConcepts: string[]): RulesetRef {
  return { id, version, name, scoringConcepts, officialScoringFromWearable: false };
}

function discipline(input: MartialArtDiscipline): MartialArtDiscipline {
  return input;
}

const strikingModes: CombatSessionMode[] = [
  "technique",
  "pad_work",
  "bag_work",
  "shadowboxing",
  "sparring",
  "drill",
  "footwork",
  "conditioning",
  "strength",
  "mobility",
  "live_round",
  "competition_prep",
  "warmup",
  "cooldown",
  "recovery"
];

const grapplingModes: CombatSessionMode[] = [
  "technique",
  "drill",
  "grappling_drill",
  "rolling",
  "live_round",
  "randori",
  "conditioning",
  "strength",
  "mobility",
  "competition_prep",
  "warmup",
  "cooldown",
  "recovery"
];

export const MARTIAL_ARTS_DISCIPLINES: MartialArtDiscipline[] = [
  discipline({
    id: "boxing",
    name: "Boxing",
    aliases: ["pugilism", "western boxing"],
    regions: ["global", "united_kingdom", "united_states"],
    tradition: "modern olympic combat sport",
    family: "striking",
    practiceKinds: ["combat_sport", "sport", "fitness_conditioning"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["amateur", "professional", "olympic"],
    rulesets: [
      ruleset("iba_amateur", "2026", "IBA / Olympic amateur boxing", ["punches_scored", "rounds"]),
      ruleset("pro_10x3", "open", "Professional 10x3", ["10_point_must", "rounds"])
    ],
    sessionModes: strikingModes,
    techniqueFamilies: ["jab", "cross", "hook", "uppercut", "overhand", "defense", "footwork"],
    equipment: ["gloves", "hand_wraps", "heavy_bag", "focus_mitts"],
    metrics: STRIKE_METRICS.filter((m) => m !== "kick_count"),
    federations: ["IBA", "IOC boxing", "WBC", "WBA", "IBF", "WBO"],
    coachSpecialization: "boxing",
    rankSystem: "boxing_none",
    telemetryNotes:
      "Punch count/rate only from a validated strike sensor or manual log. Watch IMU is acceleration, not force."
  }),
  discipline({
    id: "muay_thai",
    name: "Muay Thai",
    aliases: ["thai boxing"],
    regions: ["thailand", "global"],
    tradition: "muay",
    family: "striking",
    practiceKinds: ["combat_sport", "martial_art", "fitness_conditioning"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["stadium", "ifma_amateur"],
    rulesets: [ruleset("ifma", "2026", "IFMA amateur", ["punches", "kicks", "knees", "elbows", "clinch"])],
    sessionModes: [...strikingModes],
    techniqueFamilies: ["punches", "kicks", "knees", "elbows", "clinch", "teeps"],
    equipment: ["gloves", "shinguards", "thai_pads", "heavy_bag"],
    metrics: [...STRIKE_METRICS, "knee_count", "elbow_count"],
    federations: ["IFMA", "WMC"],
    coachSpecialization: "muay_thai",
    rankSystem: "org_specific",
    telemetryNotes: "Never apply boxing-only scoring. Knees, elbows and clinch are first-class."
  }),
  discipline({
    id: "kickboxing",
    name: "Kickboxing",
    aliases: ["K-1", "oriental rules"],
    regions: ["global", "japan", "netherlands"],
    tradition: "modern striking sport",
    family: "striking",
    practiceKinds: ["combat_sport", "fitness_conditioning"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["full_contact", "low_kick", "k1", "points"],
    rulesets: [ruleset("wako", "2026", "WAKO", ["punches", "kicks", "rounds"])],
    sessionModes: strikingModes,
    techniqueFamilies: ["punches", "kicks", "combinations", "footwork"],
    equipment: ["gloves", "shinguards", "pads"],
    metrics: STRIKE_METRICS,
    federations: ["WAKO"],
    coachSpecialization: "kickboxing",
    rankSystem: "org_specific",
    telemetryNotes: "Ruleset selects whether low kicks and knees are legal. Do not default to boxing."
  }),
  discipline({
    id: "savate",
    name: "Savate",
    aliases: ["boxe française"],
    regions: ["france"],
    tradition: "french kickboxing",
    family: "striking",
    practiceKinds: ["combat_sport", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["assault", "combat"],
    rulesets: [ruleset("fisavat", "2026", "FISav", ["punches", "kicks", "shoes"])],
    sessionModes: strikingModes,
    techniqueFamilies: ["chassé", "fouetté", "revers", "punches"],
    equipment: ["savate_shoes", "gloves"],
    metrics: STRIKE_METRICS,
    federations: ["FISav"],
    coachSpecialization: "savate",
    rankSystem: "org_specific",
    telemetryNotes: "Shod kicking is characteristic. Do not treat as generic kickboxing."
  }),
  discipline({
    id: "taekwondo",
    name: "Taekwondo",
    aliases: ["TKD"],
    regions: ["korea", "global"],
    tradition: "korean striking",
    family: "striking",
    practiceKinds: ["combat_sport", "martial_art", "sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["wt_kukkiwon", "itf"],
    rulesets: [
      ruleset("wt_kyorugi", "2026", "World Taekwondo kyorugi", ["electronic_scoring", "body", "head"]),
      ruleset("itf", "open", "ITF sparring", ["punches", "kicks"])
    ],
    sessionModes: [...strikingModes, "forms"],
    techniqueFamilies: ["front_kick", "round_kick", "turning_kick", "punches", "poomsae"],
    equipment: ["hogu", "electronic_socks", "headgear"],
    metrics: STRIKE_METRICS,
    federations: ["World Taekwondo", "ITF", "Kukkiwon"],
    coachSpecialization: "taekwondo",
    rankSystem: "tkd_geup_dan",
    telemetryNotes:
      "Official kyorugi scores require electronic scoring hardware. A watch cannot award a WT point."
  }),
  discipline({
    id: "karate",
    name: "Karate",
    aliases: ["karate-do"],
    regions: ["japan", "okinawa", "global"],
    tradition: "okinawan / japanese striking art",
    family: "striking",
    practiceKinds: ["martial_art", "combat_sport", "traditional_practice"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "light",
    styles: ["shotokan", "goju_ryu", "shito_ryu", "wado_ryu", "kyokushin"],
    rulesets: [
      ruleset("wkf_kumite", "2026", "WKF kumite", ["ippon", "waza_ari"]),
      ruleset("wkf_kata", "2026", "WKF kata", ["technical", "athletic"])
    ],
    sessionModes: [...strikingModes, "kata", "kumite"],
    techniqueFamilies: ["tsuki", "geri", "uke", "kata", "kumite"],
    equipment: ["gi", "mitts", "kata_none"],
    metrics: [...STRIKE_METRICS, ...FORM_METRICS],
    federations: ["WKF"],
    coachSpecialization: "karate",
    rankSystem: "karate_kyu_dan",
    telemetryNotes: "Kata and kumite telemetry must never be mixed. Do not invent WKF scores from IMU."
  }),
  discipline({
    id: "sanda",
    name: "Sanda",
    aliases: ["sanshou"],
    regions: ["china", "global"],
    tradition: "chinese combat sport",
    family: "mixed",
    practiceKinds: ["combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["iwuf_sanda"],
    rulesets: [ruleset("iwuf_sanda", "2026", "IWUF Sanda", ["punches", "kicks", "throws"])],
    sessionModes: [...strikingModes, "sanda", "grappling_drill"],
    techniqueFamilies: ["punches", "kicks", "throws", "wrestling"],
    equipment: ["gloves", "sanda_shorts", "headgear"],
    metrics: MIXED_METRICS,
    federations: ["IWUF"],
    coachSpecialization: "sanda",
    rankSystem: "org_specific",
    telemetryNotes: "Sanda is not boxing and not Wushu taolu. Throws are in-scope."
  }),
  discipline({
    id: "wushu",
    name: "Wushu",
    aliases: ["Chinese Wushu"],
    regions: ["china", "global"],
    tradition: "contemporary chinese martial sport",
    family: "traditional_cultural",
    practiceKinds: ["sport", "martial_art", "traditional_practice"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "none",
    styles: ["changquan", "nanquan", "taijiquan_taolu"],
    rulesets: [ruleset("iwuf_taolu", "2026", "IWUF Taolu", ["difficulty", "quality", "overall"])],
    sessionModes: ["taolu", "forms", "technique", "conditioning", "mobility", "warmup", "cooldown"],
    techniqueFamilies: ["taolu", "balance", "jump", "weapon_forms"],
    equipment: ["taolu_uniform", "optional_weapons"],
    metrics: FORM_METRICS,
    federations: ["IWUF"],
    coachSpecialization: "wushu_taolu",
    rankSystem: "org_specific",
    telemetryNotes: "Taolu is forms quality, not strike rate. Sanda is a separate discipline."
  }),
  discipline({
    id: "lethwei",
    name: "Lethwei",
    aliases: ["burmese boxing"],
    regions: ["myanmar"],
    tradition: "burmese striking",
    family: "striking",
    practiceKinds: ["combat_sport", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["traditional", "modern_promoted"],
    rulesets: [ruleset("wl_open", "open", "Lethwei promotion rules", ["punches", "kicks", "headbutts"])],
    sessionModes: strikingModes,
    techniqueFamilies: ["punches", "kicks", "knees", "elbows", "headbutts"],
    equipment: ["wraps", "optional_gloves"],
    metrics: STRIKE_METRICS,
    federations: ["World Lethwei Championship"],
    coachSpecialization: "lethwei",
    rankSystem: "org_specific",
    telemetryNotes: "Headbutts are part of the art. Safety events are IMPACT_EVENT, never a diagnosis."
  }),
  discipline({
    id: "mma",
    name: "Mixed Martial Arts",
    aliases: ["MMA"],
    regions: ["global"],
    tradition: "modern mixed combat sport",
    family: "mixed",
    practiceKinds: ["combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["unified_rules", "one_championship"],
    rulesets: [
      ruleset("unified_mma", "2026", "Unified Rules of MMA", [
        "strikes",
        "takedowns",
        "control",
        "submissions",
        "rounds"
      ])
    ],
    sessionModes: [
      ...strikingModes,
      "grappling_drill",
      "rolling",
      "live_round"
    ],
    techniqueFamilies: ["striking", "wrestling", "clinch", "ground", "submissions"],
    equipment: ["gloves_4oz", "shin_guards_training", "cage_or_mat"],
    metrics: MIXED_METRICS,
    federations: ["UFC", "ONE", "IMMAF"],
    coachSpecialization: "mma",
    rankSystem: "none",
    telemetryNotes:
      "Training wearables are not official fight statistics. UFC/Meta rankings use fight outcomes, not IMU."
  }),
  discipline({
    id: "bjj",
    name: "Brazilian Jiu-Jitsu",
    aliases: ["BJJ", "Gracie Jiu-Jitsu"],
    regions: ["brazil", "global"],
    tradition: "brazilian grappling",
    family: "grappling",
    practiceKinds: ["martial_art", "combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "moderate",
    styles: ["gi", "nogi", "ibjjf"],
    rulesets: [
      ruleset("ibjjf", "2026", "IBJJF gi", ["sweep", "pass", "mount", "back", "submission"]),
      ruleset("adcc", "2024", "ADCC", ["takedown", "pass", "submission"])
    ],
    sessionModes: grapplingModes,
    techniqueFamilies: ["guard", "pass", "sweep", "mount", "back", "submissions", "escapes"],
    equipment: ["gi", "rashguard", "mat"],
    metrics: GRAPPLE_METRICS,
    federations: ["IBJJF", "ADCC"],
    coachSpecialization: "bjj",
    rankSystem: "bjj_ibjjf",
    telemetryNotes: "Positional time and submissions are user/coach logged unless a mat sensor exists. Never auto-award belts."
  }),
  discipline({
    id: "judo",
    name: "Judo",
    aliases: ["judô"],
    regions: ["japan", "global"],
    tradition: "kodokan",
    family: "grappling",
    practiceKinds: ["martial_art", "combat_sport", "sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["kodokan", "ijf"],
    rulesets: [ruleset("ijf", "2025", "IJF Sporting Code", ["ippon", "waza_ari", "shido"])],
    sessionModes: [...grapplingModes, "randori"],
    techniqueFamilies: ["nage_waza", "katame_waza", "ukemi", "grips"],
    equipment: ["judogi", "tatami"],
    metrics: GRAPPLE_METRICS,
    federations: ["IJF", "Kodokan"],
    coachSpecialization: "judo",
    rankSystem: "judo_kyu_dan",
    telemetryNotes: "Do not invent Ippon/Waza-ari from accelerometer landings."
  }),
  discipline({
    id: "wrestling",
    name: "Wrestling",
    aliases: ["freestyle", "greco-roman"],
    regions: ["global"],
    tradition: "olympic wrestling",
    family: "grappling",
    practiceKinds: ["combat_sport", "sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["freestyle", "greco_roman", "folkstyle"],
    rulesets: [
      ruleset("uww_fs", "2026", "UWW Freestyle", ["takedown", "exposure", "pushout"]),
      ruleset("uww_gr", "2026", "UWW Greco-Roman", ["throws", "par_terre"])
    ],
    sessionModes: grapplingModes,
    techniqueFamilies: ["shot", "sprawl", "throw", "mat_return", "scramble"],
    equipment: ["singlet", "headgear", "mat"],
    metrics: GRAPPLE_METRICS,
    federations: ["UWW"],
    coachSpecialization: "wrestling",
    rankSystem: "wrestling_none",
    telemetryNotes: "Folkstyle scoring is a different ruleset. Store the version in use."
  }),
  discipline({
    id: "sambo",
    name: "Sambo",
    aliases: ["sombo"],
    regions: ["russia", "global"],
    tradition: "soviet martial sport",
    family: "grappling",
    practiceKinds: ["combat_sport", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["sport", "combat", "beach"],
    rulesets: [
      ruleset("fias_sport", "2026-08-21", "FIAS Sport SAMBO", ["throw", "hold_down", "submission"]),
      ruleset("fias_combat", "2026", "FIAS Combat SAMBO", ["strikes", "throws", "submissions"])
    ],
    sessionModes: [...grapplingModes, "live_round"],
    techniqueFamilies: ["throws", "hold_downs", "leg_locks", "standing"],
    equipment: ["sambovka", "shorts", "jacket"],
    metrics: GRAPPLE_METRICS,
    federations: ["FIAS"],
    coachSpecialization: "sambo",
    rankSystem: "sambo_sport",
    telemetryNotes:
      "FIAS amended Sport SAMBO in 2026 (hold confirmation, throw starting-position clarifications). Scoring follows the selected ruleset version, never IMU."
  }),
  discipline({
    id: "catch_wrestling",
    name: "Catch Wrestling",
    aliases: ["catch-as-catch-can"],
    regions: ["united_kingdom", "united_states"],
    tradition: "lancashire catch",
    family: "grappling",
    practiceKinds: ["martial_art", "combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["catch"],
    rulesets: [ruleset("catch_open", "open", "Catch rules (org-specific)", ["pin", "submission"])],
    sessionModes: grapplingModes,
    techniqueFamilies: ["pins", "rides", "submissions", "hooks"],
    equipment: ["singlet_or_shorts", "mat"],
    metrics: GRAPPLE_METRICS,
    federations: ["org-specific"],
    coachSpecialization: "catch_wrestling",
    rankSystem: "none",
    telemetryNotes: "Not BJJ. Pins and neck/leg rides are first-class."
  }),
  discipline({
    id: "luta_livre",
    name: "Luta Livre",
    aliases: ["Luta Livre Esportiva"],
    regions: ["brazil"],
    tradition: "brazilian submission wrestling",
    family: "grappling",
    practiceKinds: ["martial_art", "combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["esportiva", "vale_tudo_heritage"],
    rulesets: [ruleset("lle_open", "open", "Luta Livre esportiva", ["takedown", "submission"])],
    sessionModes: grapplingModes,
    techniqueFamilies: ["takedowns", "submissions", "nogi_control"],
    equipment: ["shorts", "mat"],
    metrics: GRAPPLE_METRICS,
    federations: ["org-specific"],
    coachSpecialization: "luta_livre",
    rankSystem: "org_specific",
    telemetryNotes: "No-gi grappling with its own rank orgs. Do not map blindly to IBJJF belts."
  }),
  discipline({
    id: "sumo",
    name: "Sumo",
    aliases: ["sumō"],
    regions: ["japan"],
    tradition: "japanese wrestling",
    family: "grappling",
    practiceKinds: ["sport", "traditional_practice", "cultural_practice"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["professional_ozumo", "amateur"],
    rulesets: [ruleset("jsf_amateur", "2026", "Amateur sumo", ["pushout", "throw"])],
    sessionModes: ["technique", "drill", "live_round", "conditioning", "strength"],
    techniqueFamilies: ["tachiai", "throws", "pushes"],
    equipment: ["mawashi", "dohyo"],
    metrics: ["session_duration", "rpe", "takedowns"],
    federations: ["Nihon Sumo Kyokai", "IFS"],
    coachSpecialization: "sumo",
    rankSystem: "org_specific",
    telemetryNotes: "Professional ranks (makuuchi etc.) are not invented. Amateur and pro are different systems."
  }),
  discipline({
    id: "chidaoba",
    name: "Chidaoba",
    aliases: ["Georgian wrestling"],
    regions: ["georgia"],
    tradition: "georgian wrestling",
    family: "traditional_cultural",
    practiceKinds: ["cultural_practice", "traditional_practice", "sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "full",
    styles: ["chidaoba"],
    rulesets: [ruleset("chidaoba_trad", "open", "Traditional Chidaoba", ["holds", "throws"])],
    sessionModes: ["technique", "drill", "live_round", "conditioning"],
    techniqueFamilies: ["holds", "throws", "chivalric_code"],
    equipment: ["chokha_related_or_sport_kit", "music_context"],
    metrics: FORM_METRICS,
    federations: ["National Federation of Georgian Wrestling"],
    coachSpecialization: "chidaoba",
    rankSystem: "none",
    unescoIch: { id: "01371", year: 2018, title: "Chidaoba, wrestling in Georgia" },
    culturalNote: "UNESCO ICH: wrestling combined with music, dance and a chivalric code.",
    telemetryNotes: "Do not reduce to MMA takedown counts. Cultural context is part of the session."
  }),
  discipline({
    id: "capoeira",
    name: "Capoeira",
    aliases: ["roda de capoeira"],
    regions: ["brazil"],
    tradition: "afro-brazilian",
    family: "traditional_cultural",
    practiceKinds: ["cultural_practice", "martial_art", "traditional_practice", "sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "light",
    styles: ["angola", "regional", "contemporanea"],
    rulesets: [ruleset("roda", "open", "Roda (group ritual)", ["game", "music", "malicia"])],
    sessionModes: ["roda", "technique", "mobility", "conditioning", "forms", "warmup", "cooldown"],
    techniqueFamilies: ["ginga", "kicks", "escapes", "acrobatics", "music"],
    equipment: ["berimbau", "atabaque", "pandeiro", "white_clothing"],
    metrics: FORM_METRICS,
    federations: ["community groups", "ABCA and others — org-specific"],
    coachSpecialization: "capoeira",
    rankSystem: "capoeira_cordao",
    unescoIch: { id: "00892", year: 2014, title: "Capoeira circle" },
    culturalNote:
      "UNESCO: Afro-Brazilian practice simultaneously fight, dance, tradition, sport and expression. The roda is community ritual, not a strike-rate sport.",
    telemetryNotes: "Primary signals are duration, ginga/flow, mobility and rhythm — never strikes per minute as the headline metric."
  }),
  discipline({
    id: "silat",
    name: "Silat",
    aliases: ["Malay silat"],
    regions: ["malaysia", "brunei", "singapore"],
    tradition: "malay archipelago",
    family: "traditional_cultural",
    practiceKinds: ["cultural_practice", "martial_art", "traditional_practice"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["harimau", "gayong", "lintas", "150+_malaysian_styles"],
    rulesets: [ruleset("style_specific", "open", "Style / sekolah rules", ["artistic", "self_defense", "sport"])],
    sessionModes: ["forms", "technique", "drill", "sparring", "conditioning"],
    techniqueFamilies: ["buah", "jurus", "weapon", "empty_hand"],
    equipment: ["sarong", "optional_weapons"],
    metrics: FORM_METRICS,
    federations: ["PESAKA"],
    coachSpecialization: "silat",
    rankSystem: "org_specific",
    unescoIch: { id: "01504", year: 2019, title: "Silat" },
    culturalNote: "UNESCO 2019: combative art of self-defence rooted in the Malay archipelago, with many named styles.",
    telemetryNotes: "Do not merge every Silat school into one ruleset. Style is required."
  }),
  discipline({
    id: "pencak_silat",
    name: "Pencak Silat",
    aliases: ["pencak"],
    regions: ["indonesia"],
    tradition: "indonesian martial tradition",
    family: "traditional_cultural",
    practiceKinds: ["cultural_practice", "martial_art", "combat_sport"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["regional_jurus", "ipsi_sport"],
    rulesets: [ruleset("persilat", "open", "International pencak silat sport", ["tanding", "seni"])],
    sessionModes: ["forms", "technique", "sparring", "drill", "conditioning"],
    techniqueFamilies: ["jurus", "tanding", "seni", "weapon"],
    equipment: ["pencak_uniform"],
    metrics: [...FORM_METRICS, "strike_count"],
    federations: ["IPSI", "PERSILAT"],
    coachSpecialization: "pencak_silat",
    rankSystem: "org_specific",
    unescoIch: { id: "01391", year: 2019, title: "Traditions of Pencak Silat" },
    culturalNote: "UNESCO 2019: sporting, mental-spiritual, self-defence and artistic aspects together.",
    telemetryNotes: "Seni (art) and tanding (match) are different modes. Do not mix telemetry."
  }),
  discipline({
    id: "taekkyeon",
    name: "Taekkyeon",
    aliases: ["taekkyon"],
    regions: ["korea"],
    tradition: "korean traditional martial art",
    family: "traditional_cultural",
    practiceKinds: ["traditional_practice", "cultural_practice", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "light",
    styles: ["korea_taekkyeon_association"],
    rulesets: [ruleset("taekkyeon_trad", "open", "Traditional competition / play", ["trips", "kicks"])],
    sessionModes: ["technique", "forms", "drill", "live_round", "mobility"],
    techniqueFamilies: ["pum", "kicks", "trips", "rhythm"],
    equipment: ["hanbok_related_or_training_kit"],
    metrics: FORM_METRICS,
    federations: ["Korea Taekkyeon Association"],
    coachSpecialization: "taekkyeon",
    rankSystem: "org_specific",
    unescoIch: { id: "00452", year: 2011, title: "Taekkyeon, a traditional Korean martial art" },
    culturalNote: "UNESCO 2011: fluid dance-like movements; community and seasonal tradition as well as martial practice.",
    telemetryNotes: "Not Taekwondo. Circular rhythm and trips matter more than electronic hogu scores."
  }),
  discipline({
    id: "kun_lbokator",
    name: "Kun Lbokator",
    aliases: ["Lbokator", "Bokator"],
    regions: ["cambodia"],
    tradition: "khmer martial art",
    family: "traditional_cultural",
    practiceKinds: ["traditional_practice", "cultural_practice", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["traditional"],
    rulesets: [ruleset("lbokator_trad", "open", "Traditional / festival", ["forms", "self_defense"])],
    sessionModes: ["forms", "technique", "drill", "conditioning"],
    techniqueFamilies: ["animal_forms", "self_defense", "ritual"],
    equipment: ["krama", "traditional_kit"],
    metrics: FORM_METRICS,
    federations: ["Cambodian martial arts bodies — org-specific"],
    coachSpecialization: "kun_lbokator",
    rankSystem: "org_specific",
    unescoIch: { id: "01868", year: 2022, title: "Kun Lbokator, traditional martial arts in Cambodia" },
    culturalNote: "UNESCO 2022: mental and physical discipline with ritual, music and non-violence philosophy.",
    telemetryNotes: "Force metrics are usually inappropriate. Session duration, forms and technique notes first."
  }),
  discipline({
    id: "kung_fu",
    name: "Kung Fu",
    aliases: ["gongfu", "chinese martial arts"],
    regions: ["china", "global"],
    tradition: "chinese martial systems",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "traditional_practice", "fitness_conditioning"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["shaolin", "wing_chun_related", "hung_gar", "northern", "southern"],
    rulesets: [ruleset("school", "open", "School / lineage", ["forms", "applications"])],
    sessionModes: ["forms", "technique", "drill", "conditioning", "sparring"],
    techniqueFamilies: ["taolu", "applications", "stances", "weapons"],
    equipment: ["school_uniform", "optional_weapons"],
    metrics: FORM_METRICS,
    federations: ["school-specific", "IWUF overlap for wushu"],
    coachSpecialization: "kung_fu",
    rankSystem: "org_specific",
    telemetryNotes: "Kung Fu is a family of systems, not one sport. Style is required. Distinct from Wushu taolu sport."
  }),
  discipline({
    id: "taijiquan",
    name: "Taijiquan",
    aliases: ["Tai Chi", "Tai Chi Chuan"],
    regions: ["china", "global"],
    tradition: "internal chinese martial art",
    family: "internal",
    practiceKinds: ["martial_art", "traditional_practice", "fitness_conditioning"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "none",
    styles: ["yang", "chen", "wu", "sun", "wu_hao"],
    rulesets: [ruleset("iwuf_taiji", "2026", "IWUF taiji taolu", ["quality", "difficulty"])],
    sessionModes: ["forms", "technique", "mobility", "recovery", "warmup", "cooldown"],
    techniqueFamilies: ["form", "push_hands", "silk_reeling"],
    equipment: ["none_or_uniform"],
    metrics: FORM_METRICS,
    federations: ["IWUF", "school-specific"],
    coachSpecialization: "taijiquan",
    rankSystem: "org_specific",
    telemetryNotes: "Do not apply combat strike telemetry. Movement quality, duration and balance notes only."
  }),
  discipline({
    id: "wing_chun",
    name: "Wing Chun",
    aliases: ["Ving Tsun", "Yongchun"],
    regions: ["china", "hong_kong", "global"],
    tradition: "southern chinese",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "self_defense"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "light",
    styles: ["ip_man", "other_lineages"],
    rulesets: [ruleset("lineage", "open", "Lineage curriculum", ["chi_sao", "forms"])],
    sessionModes: ["forms", "drill", "technique", "conditioning"],
    techniqueFamilies: ["sil_lim_tao", "chum_kiu", "biu_jee", "chi_sao", "wooden_dummy"],
    equipment: ["wooden_dummy"],
    metrics: FORM_METRICS,
    federations: ["lineage-specific"],
    coachSpecialization: "wing_chun",
    rankSystem: "org_specific",
    telemetryNotes: "Not a round-sport by default. Chi sao sensitivity is coach-confirmed, not IMU-classified."
  }),
  discipline({
    id: "jeet_kune_do",
    name: "Jeet Kune Do",
    aliases: ["JKD"],
    regions: ["global"],
    tradition: "bruce lee / jun fan",
    family: "mixed",
    practiceKinds: ["martial_art", "self_defense", "fitness_conditioning"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["original", "jkd_concepts"],
    rulesets: [ruleset("school", "open", "School interpretation", ["interception", "simplicity"])],
    sessionModes: ["technique", "drill", "pad_work", "sparring", "conditioning"],
    techniqueFamilies: ["straight_lead", "trapping", "kicks", "energy_drills"],
    equipment: ["gloves", "pads"],
    metrics: [...STRIKE_METRICS, ...FORM_METRICS],
    federations: ["school-specific"],
    coachSpecialization: "jeet_kune_do",
    rankSystem: "none",
    telemetryNotes: "JKD is a method, not a single federation sport. Avoid fake rank ladders."
  }),
  discipline({
    id: "hapkido",
    name: "Hapkido",
    aliases: [],
    regions: ["korea", "global"],
    tradition: "korean hybrid art",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "self_defense"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["school-specific"],
    rulesets: [ruleset("school", "open", "School curriculum", ["joint_locks", "kicks", "throws"])],
    sessionModes: ["technique", "drill", "forms", "conditioning"],
    techniqueFamilies: ["joint_locks", "throws", "kicks", "weapons"],
    equipment: ["dobok"],
    metrics: FORM_METRICS,
    federations: ["school-specific"],
    coachSpecialization: "hapkido",
    rankSystem: "org_specific",
    telemetryNotes: "Not Taekwondo. Joint manipulation quality is coach-confirmed."
  }),
  discipline({
    id: "aikido",
    name: "Aikido",
    aliases: [],
    regions: ["japan", "global"],
    tradition: "aikikai / related",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "traditional_practice"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "none",
    styles: ["aikikai", "yoshinkan", "ki_society"],
    rulesets: [ruleset("dojo", "open", "Dojo curriculum", ["ukemi", "technique"])],
    sessionModes: ["technique", "drill", "forms", "mobility"],
    techniqueFamilies: ["irimi", "tenkan", "pins", "ukemi"],
    equipment: ["gi", "hakama"],
    metrics: FORM_METRICS,
    federations: ["Aikikai", "other"],
    coachSpecialization: "aikido",
    rankSystem: "judo_kyu_dan",
    telemetryNotes: "No competitive scoring. Force and strike-rate telemetry are inappropriate."
  }),
  discipline({
    id: "kendo",
    name: "Kendo",
    aliases: [],
    regions: ["japan", "global"],
    tradition: "japanese swordsmanship sport",
    family: "traditional_cultural",
    practiceKinds: ["sport", "martial_art"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "moderate",
    styles: ["fih", "all_japan_kendo"],
    rulesets: [ruleset("fih_kendo", "2026", "FIK kendo", ["yuko_datotsu"])],
    sessionModes: ["technique", "drill", "live_round", "kata", "conditioning"],
    techniqueFamilies: ["men", "kote", "do", "tsuki", "kata"],
    equipment: ["shinai", "bogu", "hakama"],
    metrics: FORM_METRICS,
    federations: ["FIK", "AJKF"],
    coachSpecialization: "kendo",
    rankSystem: "kendo_kyu_dan",
    telemetryNotes: "Valid strikes follow FIK criteria (hasuji, ki-ken-tai). IMU cannot award yuko-datotsu."
  }),
  discipline({
    id: "iaido",
    name: "Iaido",
    aliases: ["iaijutsu"],
    regions: ["japan", "global"],
    tradition: "japanese sword drawing",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "traditional_practice"],
    competitive: true,
    noncompetitive: true,
    contactLevel: "none",
    styles: ["muso_jikiden", "seitei"],
    rulesets: [ruleset("fnk_iaido", "open", "Seitei iai grading / taikai", ["reigi", "timing", "hasuji"])],
    sessionModes: ["forms", "technique", "kata"],
    techniqueFamilies: ["nukitsuke", "kirioroshi", "chiburi", "noto"],
    equipment: ["iaito", "hakama"],
    metrics: FORM_METRICS,
    federations: ["FIK iaido", "school-specific"],
    coachSpecialization: "iaido",
    rankSystem: "kendo_kyu_dan",
    telemetryNotes: "Solo forms. Combat strike telemetry is inappropriate."
  }),
  discipline({
    id: "kalaripayattu",
    name: "Kalaripayattu",
    aliases: ["Kalari"],
    regions: ["india"],
    tradition: "kerala martial art",
    family: "traditional_cultural",
    practiceKinds: ["martial_art", "traditional_practice", "cultural_practice"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["northern", "southern"],
    rulesets: [ruleset("kalari", "open", "Kalari lineage", ["meithari", "kolthari", "ankathari"])],
    sessionModes: ["forms", "technique", "conditioning", "mobility"],
    techniqueFamilies: ["body_control", "wooden_weapons", "metal_weapons"],
    equipment: ["kalari_floor", "wooden_weapons"],
    metrics: FORM_METRICS,
    federations: ["lineage / state bodies"],
    coachSpecialization: "kalaripayattu",
    rankSystem: "org_specific",
    telemetryNotes: "Traditional staged curriculum. Do not flatten into MMA rounds."
  }),
  discipline({
    id: "krav_maga",
    name: "Krav Maga",
    aliases: [],
    regions: ["israel", "global"],
    tradition: "modern self-defence system",
    family: "self_defense",
    practiceKinds: ["self_defense", "fitness_conditioning"],
    competitive: false,
    noncompetitive: true,
    contactLevel: "varies",
    styles: ["ikmf", "krav_maga_global", "other"],
    rulesets: [ruleset("org", "open", "Organisation curriculum", ["defenses", "stress_drills"])],
    sessionModes: ["technique", "drill", "conditioning", "pad_work"],
    techniqueFamilies: ["defenses", "strikes", "ground_getup"],
    equipment: ["pads", "gloves"],
    metrics: [...FORM_METRICS, "strike_count"],
    federations: ["IKMF", "KMG", "others"],
    coachSpecialization: "krav_maga",
    rankSystem: "org_specific",
    telemetryNotes: "Not a combat sport with unified scoring. Org rank systems differ. No fake belts."
  })
];

const REQUIRED_IDS = [
  "boxing",
  "muay_thai",
  "kickboxing",
  "mma",
  "bjj",
  "judo",
  "karate",
  "taekwondo",
  "wrestling",
  "sambo",
  "sanda",
  "wushu",
  "savate",
  "capoeira",
  "silat",
  "pencak_silat",
  "lethwei",
  "hapkido",
  "aikido",
  "kung_fu",
  "taijiquan",
  "kendo",
  "iaido",
  "taekkyeon",
  "kun_lbokator",
  "chidaoba",
  "kalaripayattu",
  "krav_maga",
  "wing_chun",
  "jeet_kune_do",
  "sumo"
] as const;

export function getDiscipline(id: string): MartialArtDiscipline | undefined {
  const key = id.trim().toLowerCase().replace(/[\s-]+/g, "_");
  return MARTIAL_ARTS_DISCIPLINES.find(
    (d) => d.id === key || d.aliases.some((a) => a.toLowerCase().replace(/[\s-]+/g, "_") === key)
  );
}

export function listDisciplines(filter?: {
  family?: CombatFamily;
  practiceKind?: PracticeKind;
  competitive?: boolean;
}): MartialArtDiscipline[] {
  return MARTIAL_ARTS_DISCIPLINES.filter((d) => {
    if (filter?.family && d.family !== filter.family) return false;
    if (filter?.practiceKind && !d.practiceKinds.includes(filter.practiceKind)) return false;
    if (filter?.competitive != null && d.competitive !== filter.competitive) return false;
    return true;
  });
}

export function catalogIndex() {
  return {
    version: MARTIAL_ARTS_CATALOG_VERSION,
    sport: "MARTIAL_ARTS" as const,
    count: MARTIAL_ARTS_DISCIPLINES.length,
    families: {
      striking: listDisciplines({ family: "striking" }).map((d) => d.id),
      grappling: listDisciplines({ family: "grappling" }).map((d) => d.id),
      mixed: listDisciplines({ family: "mixed" }).map((d) => d.id),
      traditional_cultural: listDisciplines({ family: "traditional_cultural" }).map((d) => d.id),
      self_defense: listDisciplines({ family: "self_defense" }).map((d) => d.id),
      internal: listDisciplines({ family: "internal" }).map((d) => d.id)
    },
    requiredCovered: REQUIRED_IDS.every((id) => MARTIAL_ARTS_DISCIPLINES.some((d) => d.id === id))
  };
}

export function defaultRoundPrescription(disciplineId: string): {
  roundCount: number;
  workSec: number;
  restSec: number;
  warningSec: number;
  countdownSec: number;
  sessionMode: CombatSessionMode;
} {
  const d = getDiscipline(disciplineId);
  if (!d) {
    return { roundCount: 3, workSec: 180, restSec: 60, warningSec: 10, countdownSec: 10, sessionMode: "technique" };
  }
  if (d.id === "capoeira" || d.family === "internal" || d.id === "iaido" || d.id === "taijiquan") {
    return { roundCount: 1, workSec: 1200, restSec: 0, warningSec: 30, countdownSec: 5, sessionMode: d.sessionModes[0]! };
  }
  if (d.family === "grappling") {
    return { roundCount: 5, workSec: 300, restSec: 60, warningSec: 10, countdownSec: 10, sessionMode: "rolling" };
  }
  if (d.id === "mma") {
    return { roundCount: 5, workSec: 300, restSec: 60, warningSec: 10, countdownSec: 10, sessionMode: "live_round" };
  }
  return { roundCount: 5, workSec: 180, restSec: 60, warningSec: 10, countdownSec: 10, sessionMode: "bag_work" };
}

export { REQUIRED_IDS as REQUIRED_DISCIPLINE_IDS };
