# FitConnect release R8 / ProGuard — keep Compose, OkHttp, security, and DI entry points.
-keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*
-keep class com.fitconnect.android.FitConnectApplication { *; }
-keep class com.fitconnect.android.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn com.google.errorprone.annotations.**
-dontwarn com.google.crypto.tink.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep class androidx.security.** { *; }
-keepclassmembers class * extends androidx.compose.runtime.internal.ComposableFunction { *; }
